#!/usr/bin/env bash
# Display Superstitious numbers
i=1
while [ $i -le 20 ]
case $i in
4)
echo "$i"
echo "bad luck from China"
;;
9)
echo "$i"
echo "bad luck from Japan"
;;
17)
echo "$i"
echo "bad luch from Italy"
;;
*)
echo "$i"
;;
esac
((i++))
done
